project_id = "hmnatpaiatgpeshrqllx"

[functions.reset-password]
verify_jwt = false

[functions.create-member]
verify_jwt = false

[functions.delete-member]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.lookup-email]
verify_jwt = false
